#!/bin/bash

# HOPE NGO GitHub Upload Script
# This script helps you create a GitHub repository and push your code

echo "🚀 HOPE NGO GitHub Upload Guide"
echo "================================"
echo ""
echo "Follow these steps to upload your project to GitHub:"
echo ""
echo "STEP 1: Create Repository on GitHub"
echo "------------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Login with:"
echo "   Username: omkarmane369"
echo "   Password: [Your password]"
echo ""
echo "3. Fill in repository details:"
echo "   Repository name: HOPE"
echo "   Description: NGO Finance Management System - Complete solution for donations, campaigns, and donor management"
echo "   Visibility: Public (or Private if you prefer)"
echo "   ✅ Skip adding README, .gitignore, and license (we already have them)"
echo ""
echo "4. Click 'Create repository'"
echo ""
echo "STEP 2: Push Your Code"
echo "----------------------"
echo "After creating the repository, run these commands:"
echo ""
echo "cd /home/vishal/Desktop/HOPE"
echo "git remote add origin https://github.com/omkarmane369/HOPE.git"
echo "git push -u origin main"
echo ""
echo "You'll be prompted for your GitHub credentials:"
echo "Username: omkarmane369"
echo "Password: [Use Personal Access Token, not password]"
echo ""
echo "STEP 3: Get Personal Access Token (if needed)"
echo "----------------------------------------------"
echo "GitHub no longer accepts passwords for HTTPS authentication."
echo "You need a Personal Access Token:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' (classic)"
echo "3. Name: 'HOPE Upload'"
echo "4. Select scopes: ✅ repo (all)"
echo "5. Click 'Generate token'"
echo "6. COPY THE TOKEN (you won't see it again!)"
echo "7. Use this token as your password when pushing"
echo ""
echo "================================"
echo "✅ Your code is ready to push!"
echo "================================"
